services:
  app:
    container_name: logasme
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        VAIL_NODE_VERSION: 20
    # ports:
    #   - '3000:3000'
    volumes:
      - .:/var/www/html
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true